language: node_js
node_js:
  - "12.13"
branches:
  only:
    - master

script:
  #- "yarn lint"
  - "yarn test"

deploy:
  provider: heroku
  api_key:
    secure: "BBRwr_piyxQvXufbt8ARMg"
  app: qrup-app
  on:
    repo: MidasCompany/qrup-backend
